#define DEFAULT_NAME_COUNT      prefixes.size() * declinations.size() * suffixes.size()
#define PREFIX_ARR_SIZE         prefixes.size()
#define DECLINATIONS_ARR_SIZE   declinations.size()
#define SUFFIXES_ARR_SIZE       suffixes.size()
#define NAMES_ARR_SIZE          names.size()
